{"name": "test_login_failture", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <test_allure.test_feature.TestLogin object at 0x000001EC46F2A820>\n\n    @allure.story(\"密码缺失\")\n    def test_login_failture(self):\n        with allure.step(\"点击用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"点击登录之后登录失败\"):\n>           assert '1' == 1\nE           AssertionError: assert '1' == 1\n\ntest_feature.py:29: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1591894565283, "stop": 1591894565283}, {"name": "点击密码", "status": "passed", "start": 1591894565284, "stop": 1591894565284}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"E:\\python_project\\pythoncode\\test_allure\\test_feature.py\", line 29, in test_login_failture\n    assert '1' == 1\n"}, "start": 1591894565284, "stop": 1591894565284}], "attachments": [{"name": "stdout", "source": "317e8a0b-a5be-43b6-a0ea-07e6e406e285-attachment.txt", "type": "text/plain"}], "start": 1591894565283, "stop": 1591894565284, "uuid": "2af96f13-8638-48aa-bab3-d23066b150c6", "historyId": "51a3008f4194ebe85ec9457f84800b1d", "testCaseId": "c66dcffcbb3d2ec6eb32d4c0d7374dda", "fullName": "test_feature.TestLogin#test_login_failture", "labels": [{"name": "story", "value": "密码缺失"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "test_feature"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-UGIE581"}, {"name": "thread", "value": "1724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_feature"}]}